fix(s3)!: update s3-upload

diff --git a/src/s3/s3-upload b/src/s3/s3-upload
--- a/src/s3/s3-upload
+++ b/src/s3/s3-upload
@@ -1,72 +1,104 @@
 #!/bin/bash
 
-# Constants - Change these
-domain="s3.ir-thr-at1.arvanstorage.ir"
-bucket_name="hamid-aws"
-bucket_path="files"
-
-# Functions
-check_path() {
-    local path="$1"
-
-    if [ -e "$path" ]; then
-        if [ -f "$path" ]; then
-            echo 0
-        elif [ -d "$path" ]; then
-            echo 1
-        else
-            echo 3
-        fi
-    else
-        echo 3
-    fi
-}
-
-# Check if yt-dlp is installed
-if ! command-exists aws &>/dev/null; then
+if ! command -v aws &>/dev/null; then
     echo "Error: aws is not installed. Please install it first."
     exit 1
 fi
 
-# Check if a YouTube link is provided
-if [ $# -eq 0 ]; then
-    echo "Usage: $0 <file or path to upload> <options>"
-    echo "Sample:"
-    printf "\t%s file.mp4\n" "$0"
-    printf "\t%s folder\n" "$0"
-    printf "\t%s folder--exclude "*.tmp"\n" "$0"
+# =============== Default values ===============
+domain="$S3_DOMAIN"
+bucket_name="$S3_BUCKET_PATH"
+bucket_path="$S3_BUCKET_PATH"
+remove_after_upload=false
+exit_on_error=false
+
+# =============== Functions ===============
+show_help() {
+    echo "Usage: $(basename "$0") [OPTIONS] [FILES or FOLDERS]"
+    echo
+    echo "This script uploads files or folders to an S3 bucket using AWS CLI."
+    echo
+    echo "Options:"
+    echo "  -d, --domain          Specify the S3 domain (endpoint URL)."
+    echo "  -n, --bucket-name     Specify the S3 bucket name."
+    echo "  -p, --bucket-path     Specify the path within the bucket."
+    echo "  --clean               Remove files/folders after successful upload."
+    echo "  --exit-on-error       Exit immediately if any command fails."
+    echo "  -h                    Display this help and exit."
+    echo
+    echo "Examples:"
+    echo "  $0 -d https://s3.amazonaws.com -n my-bucket -p backups --clean --exit-on-error file1.txt folder2"
+    echo
     exit 1
+}
+
+upload_file(){
+  local endpoint_url="$1"
+  local bucket_name="$2"
+  local bucket_path="$3"
+  local file_path="$4"
+  
+  aws --endpoint-url "$endpoint_url" s3 cp "$file_path" "s3://$bucket_name/$bucket_path/" --acl public-read
+}
+
+upload_folder(){
+  local endpoint_url="$1"
+  local bucket_name="$2"
+  local bucket_path="$3"
+  local folder_path="$4"
+  
+  aws --endpoint-url "$endpoint_url" s3 cp --recursive "$folder_path" "s3://$bucket_name/$bucket_path/" --acl public-read
+}
+
+# =============== Main ===============
+# Parse arguments
+while [[ "$#" -gt 1 ]]; do
+    case "$1" in
+        -d | --domain) domain="$2"; shift 2;;
+        -n | --bucket-name) bucket_name="$2"; shift 2;;
+        -p | --bucket-path) bucket_path="$2"; shift 2;;
+        --clean) remove_after_upload=true; shift 1;;
+        --exit-on-error) exit_on_error=true; shift 1;;
+        -h) show_help;;
+        *) echo "Unknown option: $1"; show_help;;
+    esac
+done
+
+if [ -z "$bucket_path" ]; then
+    bucket_path="files"
 fi
 
-path="$1"
-if [ "$(check_path "$path")" -eq 0 ]; then
-    folder=0 #file
-elif [ "$(check_path "$path")" -eq 1 ]; then
-    folder=1 #folder
-else
-    echo "Input ($path) is not valid. Only file or folder are allowed."
-    exit 1
+if [[ -z "$domain" || -z "$bucket_name" || $# -eq 0 ]]; then
+  show_help
 fi
 
-shift 1 # skip the path argument to get options
-
-if [ $folder -eq 0 ]; then
-    # Upload File
-    aws --endpoint-url "https://$domain" s3 cp "$path" "s3://$bucket_name/$bucket_path/" "$@"
-else
-    # Upload folder
-    aws --endpoint-url "https://$domain" s3 cp --recursive "$path" "s3://$bucket_name/$bucket_path/" "$@"
+# Check if domain starts with http or https, if not prepend https://
+if [[ ! "$domain" =~ ^http ]]; then
+    domain="https://$domain"
 fi
 
-if [ "$?" -eq 0 ]; then
-    echo "File(s) uploaded successfully."
-    if [ $folder -eq 0 ]; then
-        echo "Download URL: https://$bucket_name.$domain/$bucket_path/$(basename "$path")"
+if [ "$exit_on_error" = true ]; then
+  set -e
+fi
+
+for input in "$@"; do
+  find . -name "$input" | while read item; do
+    echo "Uploading $item..."
+    if [ -f "$item" ]; then
+      upload_file "$domain" "$bucket_name" "$bucket_path" "$item"
+    elif [ -d "$item" ]; then
+      upload_folder "$domain" "$bucket_name" "$bucket_path" "$item"
+    else
+      printf "The input '%s' is not valid. Please enter a valid file or folder.\n\n" "$item"
+      continue 
     fi
-
-    echo ""
-    aws --endpoint-url "https://$domain" s3 ls s3://$bucket_name/$bucket_path/
-else
-    echo "Error: Failed to upload file."
-    exit 1
-fi
+    
+    if [ $? -eq 0 ]; then
+      if [ "$remove_after_upload" = true ]; then
+        rm -rf "$item"
+      fi
+      
+      printf "Done.\n\n"
+    fi
+  done
+done
